services:
  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
    - "8090:8090" # keycloak
    - "8080:8080" # app

  backend:
    build: ./backend
    volumes:
      - ~/.m2:/root/.m2
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fluxcrm
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8090
    depends_on:
      - keycloak
      - db
    network_mode: "service:localhost"
  keycloak:
    image: keycloak/keycloak:26.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      ENV KC_HEALTH_ENABLED: true
      ENV KC_METRICS_ENABLED: true
    command: [
      "start-dev",
      "--http-port=8090"
    ]
    network_mode: "service:localhost"
    depends_on:
    - keycloakdb
  # fronted:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes: 
  #     - ./frontend:/app

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fluxcrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  keycloakdb:
    image: postgres:17
    ports:
      - "5433:5432" # Используйте другой порт, чтобы не конфликтовать с основной базой данных
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  keycloak-postgres-data:
    driver: local